### ISSUE TITLE
Initial Browser and DNS experience

### ISSUE THREAD

**Issue by PedroHLC** [HackerExperience/HEBorn#227]
What we already have:
*	DNS result decoded to `Okay`
*	VPC/NPC differing
*	Browser's Tabs have Id
*	Loading page (`UnknownModel`)
*	Pages can have their own models
*	Start cracker process (dispatch brute-force request)

Tasks :
-	[x] add to DNS request
```elm
{ browser: WindowId, tab: Int }
```
-	[x] add this to response
-	[x] parse 404 result
-	[x] get rid of Game.Web.*
-	[x] adapt browser for requesting pages
-	[x] adapt browser for loading
-	[x] dispatch result to browser
-	[x] adapt browser for receiving pages
-	[x] parse metadata
	-	[x] psw placeholder
		-	[x] adapt page browser model and dns metadata to handle this
-	[x] parse more hackables npcs
-	[x] parse their metadatas too
-	[x] Rename type `Browser` to `Tab`
-	[x] Add spinning icon to Loading page
	-	[x] Loading pages can't be on history
	-	[x] Can only insert fetched page when on loading && url matches
-	[x] Remove dummies
-	[x] Apps.Browser.Pages.Default.View add onClick to Crack btn
-	[ ] Use `Endpoint.member` in `A.B.Pages.Default.View` to hide password field

**Comment by PedroHLC** [comment]
@renatomassaro 
These are valid DNS responses, I removed the `meta` field, elm [`andThen` docs example](http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Json-Decode#andThen) teach us to do it in this way:
```json
{ "type":"home" }
{ "type":"web"
, "password":"helloworld"
, "custom":"ilikepink"
}
{ "type":"noweb"
, "password":"bondjames"
}
{ "type":"profile" }
{ "type":"whois" }
{ "type":"downcenter" }
{ "type":"home" }
{ "type":"isp" }
{ "type":"bank"
, "title":"Saint André"
, "location":[41.23,-20.75]
}
{ "type":"store" }
{ "type":"btc" }
{ "type":"fbi" }
{ "type":"news" }
{ "type":"bithub" }
{ "type":"missions" }
```

**Comment by PedroHLC** [comment]
via Hubstaff
User: Pedro Henrique Lara Campos

Project: HEBorn - https://app.hubstaff.com/projects/215015
Date Range: 09/18/17 - 09/19/17
Work session total: 14:34:48

Grand total: 14:34:48
