### ISSUE TITLE
Recreate notifications 

### ISSUE THREAD

**Issue by PedroHLC** [HackerExperience/HEBorn#228]
What we already have:
*	an almost-useless `OS.Header.Notifications`

Tasks:
-	[x] Create model
		`Dict Id { content: Union, action: Union, time: Time, read: Bool }`
	-	`filterUnreaded`
	-	`countUnreaded`
	-	`hasUnreaded`
	-	`read id`
	-	`getOrdered`
	-	metadata on content
	-	optimistic
	-	[x] Choose namespace to place
-	Apply this type to:
	-	[x] Game.Servers.Models.Server.notifications
	-	[x] Game.Account.Models.Model.notifications
	-	[ ] Game.Chat.Models.Model.notifications
-	[x] Discard `OS.Header.Notifications`
-	Adapt `OS.Header.View`
	-	[x] Create account gear
	-	[x] Separate per chat, servers, account gear
	-	[x] Add counted bubble
	-	[ ] Add per endpoints bubble
	
-	Create toast viewing as  `OS.Toast`
	-	[x] Model
		`{ toShow : (id: NotificationId, until: Time) }`
	-	[x] View
		- 	[x] onHover mark read
		-	[x] opacity/display with until
		-	[x] add to OS
	-	[x] Style
	-	[x] Updates
		- Insert
		- Clean olders when inserting
-	[x] Notifications bootstrap
	-	[x] Discuss format with backend
-	Notifications `.Updates`
	-	[x] Servers
	-	[x] Account
	-	[ ] Chat
	-	[ ] Dispatch new toast
-	New notification event
	-	[x] Response format
		-	[x] Discuss format with backend
	-	[x] Decoders

**Comment by PedroHLC** [comment]
via Hubstaff
User: Pedro Henrique Lara Campos

Project: HEBorn - https://app.hubstaff.com/projects/215015
Date Range: 09/21/17 - 09/24/17
Work session total: 11:08:01

Grand total: 11:08:01
