### ISSUE TITLE
[EPIC] - Continuous Delivery for HEBorn

### ISSUE THREAD

**Issue by renatomassaro** [HackerExperience/HEBorn#28]
# Description
Build, test and release automatically. Improves overall project quality and confidence, as well as enabling us to iterate quickly. CD makes a dozen of releases per day become boring.

# Tasks

- [x] Prepare build server
- [x] Prepare prod server
- [x] Automate release with a Jenkinsfile
