### ISSUE TITLE
Storage roadmap

### ISSUE THREAD

**Issue by PedroHLC** [HackerExperience/HEBorn#319]
Though HEBorn was made with every server having one File System, Helix was made with servers mounting physical storage devices which have their filesystem and a "preferred" one (for Downloads, etc). This change requires:
* [x] Create "mounted storages" list, and active storage (maybe id)
* [x] Complete drop of servers.filesystem
* * [x] Drop direct access to .filesystem
* * [x] Servers.getFilesystem return active storage filesystem (?: with an empty as default or Maybe)
* * [x] Filesystem messages are Storage messages and required their storage ID
* * [x] Adapt uses of Filesystem messages
* [x] Adapt Explorer
* [x] Adapt Explorer to switch between Storage in left sidebar (#328)
* [x] Storage selection modal (#329)

**Comment by kress95** [comment]
- possible storage model:

```
type alias Storage =
  { name : String
  , filesystem : Filesystem.Model
  }
```

- remove game.filesystem

- add game.storages : StorageId

- add game.mainStorage : Dict StorageId Storage

- change getFilesystem to fetch the main storage, fallback
  to initial model to avoid maybes

- add getStorage : StorageId -> Model -> Maybe Filesystem.Model

- discuss: add a storage folder or not?

- change FilesystemMsg to include storageID

- change explorer to show storages
  
  - add model field to select storage
  - change sidebar to show storages

- change server decoder to receive following format

```
  { ...
  , ~~filesystem~~
  , mainStorage : String
  , storage :
    { name : String
    , filesystem : Decoders.Filesystem.model
    }
  , ...
  }
```

- change NewDownloadProcess and NewPublicDownloadProcess dispatch
  to include storage_id
  
  - change payload to include storage id

- change browser to include storage selector for download

  - use the modal system from predo

- change FileDownloaded.Data to include storage information

- change FileAdded.Data to include storage information

- change notifications to include storage information
  
  - Content.DownloadStarted and Content.DownloadConcluded should include
  storage data.

- change toasts to include storage information?

  > I don't know if it should be done, maybe displaying the file name is
  > enough. Note that updating notifications is enough to adapt toasts.

  - Update view to use storage id somehow


### Discussion topics:

- Add a storage folder or not?

**Comment by kress95** [comment]
Note: Avoided full breakage of FilesystemMsg.

**Comment by kress95** [comment]
Note 2: `Servers.getFilesystem` has a different utility now

**Comment by renatomassaro** [comment]
Closed with 334?
