### ISSUE TITLE
[EPIC] - File Explorer

### ISSUE THREAD

**Issue by renatomassaro** [HackerExperience/HEBorn#39]
- [x] #34 UI mockups
- [ ] #35 Make Game.Software models at par with backend
- [x] #36 Add support for common file operations
- [ ] #37 Implement design of File Explorer
- [x] #38 Add game mechanics behaviors to File Explorer
