### ISSUE TITLE
[EPIC] - Log Viewer

### ISSUE THREAD

**Issue by renatomassaro** [HackerExperience/HEBorn#45]
- [ ] #40 UI mockup
- [ ] #41 Make Game.Log models at par with backend
- [ ] #42 Add support for common log operations
- [ ] #43 Implement design of Log Viewer
- [ ] #44 Add game mechanics behaviors to Log Viewer
